import StudentStory from '@/components/student-story';
import {Play,BookOpen,LockKeyhole,ArrowUpRight} from 'lucide-react';
import BrandGallery from '@/components/brand-gallery';
import {CourseCard} from '@/components/ui';
import Reviews from '@/components/reviews';
import {previews,type Course} from '@/lib/data';
import {catalog} from '@/lib/server';
export const dynamic='force-dynamic';
const questions=[['Where do I begin?','Explore the course previews and choose the technique you want to develop. Each course page includes its level and outline.'],['Where will I find my lessons?','Once your purchase is confirmed, your course appears in My learning. Sign in to return to your lessons and saved progress.'],['Can I learn on my phone?','Yes. Your learning space works on mobile, tablet and desktop. An internet connection is needed for online lessons.'],['When can I enrol?','Courses open when their lesson content and secure checkout are ready. Until then, you can explore the previews.']];
export default async function Home(){let courses:Course[]=previews;let unavailable=false;try{const real=await catalog();if(real.length)courses=real as Course[];}catch{unavailable=true;}
return <div className="editorial-home"><section className="growth-hero"><div className="growth-copy"><span className="growth-eyebrow">SAVANNAH SKY TRAINING ACADEMY</span><h1>Where nail techs<br/>come to <em>grow,</em><br/><span>not just to learn.</span></h1><p>Professional nail training in a kind, welcoming community. A safe place to ask questions, make mistakes and grow in confidence — where everyone is valued, whatever their starting point.</p><div className="growth-actions"><a className="button" href="/courses">Find your next step <ArrowUpRight size={18}/></a><a href="/about">The heart behind the academy</a></div><div className="growth-note"><span>01 / OUR BELIEF</span><p>Good training starts with kindness.<br/>Confidence grows from there.</p></div></div><div className="growth-art"><img className="growth-main" src="/nail-sculpted-960.webp" srcSet="/nail-sculpted-480.webp 480w, /nail-sculpted-960.webp 960w" sizes="(max-width:650px) 60vw, 45vw" width={960} height={960} fetchPriority="high" decoding="async" alt="French manicure with sculpted gold details by Savannah Sky"/><div className="growth-inset"><img src="/nail-floral-480.webp" width={480} height={480} alt="Floral nail artistry by Savannah Sky"/><span>Room to try. Space to grow.</span></div><span className="growth-caption">YOUR CRAFT. YOUR CONFIDENCE. YOUR COMMUNITY.</span></div></section><div className="growth-values">Kindness <span>·</span> Confidence <span>·</span> Community <span>·</span> Equality <span>·</span> Continuous growth</div>
<section className="editorial-benefits editorial-section"><span className="editorial-label">You belong here</span><h2>More than a course.</h2><div className="editorial-benefit-grid">{[[Play,'Space to ask','No question is too small. Learning should feel welcoming, never intimidating.'],[BookOpen,'Confidence to try','Make mistakes, practise again and recognise your progress. Everyone starts somewhere.'],[LockKeyhole,'Room for everyone','Beginners and experienced nail techs both bring something valuable to the table.']].map(([Icon,title,copy]:any)=><article key={title}><Icon size={27} strokeWidth={1}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="editorial-manifesto editorial-section"><span className="editorial-label">The heart of Savannah Sky</span><h2>Learn together.<br/>Grow together.<br/><em>Lift each other up.</em></h2><div><p>Excellent training and high standards, with kindness at the centre. We believe in equality, sharing knowledge and celebrating each other’s achievements — without competition or judgement. Everyone has something to offer, and nobody should feel left behind.</p><a className="soft-link" href="/about">Discover the academy <ArrowUpRight size={16}/></a></div></section>
<section className="editorial-gallery" aria-label="Nail artistry by Savannah Sky"><BrandGallery/></section>
<section className="editorial-story editorial-section"><div><span className="editorial-label">A message from our founder</span><h2>Your starting point<br/>isn’t your <em>whole story.</em></h2></div><div><p>I left school without a single GCSE. Today, I own a salon and I’m building an academy. I know how much it matters to have someone believe in you — and that is the feeling I want to bring to every student.</p><a className="button" href="/courses">Explore your next step <ArrowUpRight size={16}/></a></div><figure><img src="/nail-sculpted-960.webp" width={960} height={960} loading="lazy" alt="French nails finished with sculpted gold detailing"/><figcaption>Nail artistry, made with care</figcaption></figure></section>
<section id="collection" className="editorial-courses editorial-section"><div className="editorial-centered"><span className="editorial-label">The course collection</span><h2>Your next step.<br/><em>At your own pace.</em></h2><p>Starting fresh or building on experience? Explore the training and find the right place for you.</p></div>{unavailable&&<p className="notice">Course previews are available while we prepare the academy.</p>}<div className="course-grid">{courses.slice(0,3).map((c,i)=><CourseCard course={c} index={i} key={c.id}/>)}</div><div className="editorial-centered"><a className="button outline" href="/courses">View the collection <ArrowUpRight size={16}/></a></div></section>
<section className="editorial-banner"><img src="/salon-lounge-1440.webp" srcSet="/salon-lounge-480.webp 480w, /salon-lounge-960.webp 960w, /salon-lounge-1440.webp 1440w" sizes="100vw" width={1440} height={960} loading="lazy" alt="The Savannah Sky salon lounge"/><div><span className="editorial-label">Make it your own</span><h2>You have more<br/><em>in you than you know.</em></h2></div></section>
<section className="editorial-academy editorial-section"><div><span className="editorial-label">Behind the academy</span><h2>A real person.<br/><em>A shared purpose.</em></h2><p>An academy shaped by lived experience, a love of the craft and the belief that our past does not define our potential.</p><a className="soft-link" href="/about">Read my story <ArrowUpRight size={16}/></a></div><img src="/academy-portrait-960.webp" width={960} height={1440} loading="lazy" alt="The educator behind Savannah Sky in the salon"/></section>
<section className="founder-quote"><span className="eyebrow">WORDS WE CARRY WITH US</span><blockquote>“What you did yesterday will be your past, but it does not define you.”</blockquote><p>A belief at the heart of Savannah Sky Training Academy.</p></section><StudentStory/><Reviews/>
<section className="editorial-faq editorial-section"><div className="editorial-centered"><span className="editorial-label">Good to know</span><h2>A few little <em>questions.</em></h2></div><div>{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><a className="soft-link" href="/faq">All your questions, answered <ArrowUpRight size={16}/></a></section>
<section className="editorial-join editorial-section"><span className="editorial-label">Make space for yourself</span><h2>Come as you are.<br/><em>Grow into what’s next.</em></h2><a className="button" href="/courses">Find your next step <ArrowUpRight size={16}/></a></section>
<div className="editorial-photo-strip" aria-hidden="true">{['floral','sculpted','leopard','red'].map(name=><img key={name} src={'/nail-'+name+'-480.webp'} width={480} height={480} alt="" loading="lazy"/>)}</div></div>}
