import {Play,BookOpen,LockKeyhole,ArrowUpRight} from 'lucide-react';
import BrandGallery from '@/components/brand-gallery';
import {CourseCard} from '@/components/ui';
import Reviews from '@/components/reviews';
import {previews,type Course} from '@/lib/data';
import {catalog} from '@/lib/server';
export const dynamic='force-dynamic';
const questions=[['Where do I begin?','Explore the course previews and choose the technique you want to develop. Each course page includes its level and outline.'],['Where will I find my lessons?','Once your purchase is confirmed, your course appears in My learning. Sign in to return to your lessons and saved progress.'],['Can I learn on my phone?','Yes. Your learning space works on mobile, tablet and desktop. An internet connection is needed for online lessons.'],['When can I enrol?','Courses open when their lesson content and secure checkout are ready. Until then, you can explore the previews.']];
export default async function Home(){let courses:Course[]=previews;let unavailable=false;try{const real=await catalog();if(real.length)courses=real as Course[];}catch{unavailable=true;}
return <div className="editorial-home"><section className="studio-hero"><div className="studio-hero-copy"><span className="studio-eyebrow"><i/> An independent nail academy</span><h1>A little practice.<br/>A beautiful<br/><span>difference.</span></h1><p>Build your technique. Find your confidence.<br/>Nail education, made for your next chapter.</p><div className="studio-actions"><a className="button" href="/courses">Discover the courses <ArrowUpRight size={18}/></a><a className="studio-text-link" href="/about">Inside the academy</a></div><div className="studio-hero-bottom"><span>01 / Learn at your pace</span><span>02 / Make it your own</span></div></div><div className="studio-composition"><div className="studio-photo-backdrop"/><figure className="studio-main-frame"><img src="/nail-sculpted-960.webp" srcSet="/nail-sculpted-480.webp 480w, /nail-sculpted-960.webp 960w, /nail-sculpted-1440.webp 1440w" sizes="(max-width: 700px) 85vw, 43vw" width={960} height={955} alt="Savannah Sky French manicure with sculpted gold detailing" fetchPriority="high"/><figcaption><span>THE SIGNATURE EDIT</span><span>By Savannah Sky ↗</span></figcaption></figure><a className="studio-detail-frame" href="/courses/nail-art"><img src="/nail-floral-480.webp" width={480} height={480} alt="Explore delicate floral nail art"/><span>A closer look <ArrowUpRight size={14}/></span></a><div className="studio-art-note"><span>Technique.</span><span>Artistry.</span><span>You.</span></div></div></section><div className="studio-ribbon"><span>Thoughtful education</span><i/><span>Beautiful details</span><i/><span>Space to grow</span><i/><span>Your own pace</span></div>
<section className="editorial-benefits editorial-section"><span className="editorial-label">A space to grow</span><h2>Why learn with us?</h2><div className="editorial-benefit-grid">{[[Play,'Every detail, again','Pause, practise and return to the techniques you want to master.'],[BookOpen,'At your own pace','Build your skills around your day, with progress saved as you go.'],[LockKeyhole,'A place for your craft','Keep your purchased courses together in your own learning space.']].map(([Icon,title,copy]:any)=><article key={title}><Icon size={27} strokeWidth={1}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="editorial-manifesto editorial-section"><span className="editorial-label">More than a beautiful set</span><h2>Small details.<br/>New possibilities.<br/><em>Your next chapter.</em></h2><div><p>For the quiet satisfaction of a clean finish. For the confidence to try something new. Discover a thoughtful approach to nail education, from our salon to your space.</p><a className="soft-link" href="/about">Discover the academy <ArrowUpRight size={16}/></a></div></section>
<section className="editorial-gallery" aria-label="Nail artistry by Savannah Sky"><BrandGallery/></section>
<section className="editorial-story editorial-section"><div><span className="editorial-label">Beauty in the making</span><h2>Elegance begins<br/>with the <em>details.</em></h2></div><div><p>A steady hand. A considered colour. A finish that feels like you. Make room for a little creativity, one technique at a time.</p><a className="button" href="/courses">Find your next skill <ArrowUpRight size={16}/></a></div><figure><img src="/nail-sculpted-960.webp" width={960} height={960} loading="lazy" alt="French nails finished with sculpted gold detailing"/><figcaption>The Savannah Sky edit / 01</figcaption></figure></section>
<section className="editorial-courses editorial-section"><div className="editorial-centered"><span className="editorial-label">The course collection</span><h2>A little time.<br/><em>A lasting skill.</em></h2><p>Discover where you would like to begin.</p></div>{unavailable&&<p className="notice">Course previews are available while we prepare the academy.</p>}<div className="course-grid">{courses.slice(0,3).map((c,i)=><CourseCard course={c} index={i} key={c.id}/>)}</div><div className="editorial-centered"><a className="button outline" href="/courses">View the collection <ArrowUpRight size={16}/></a></div></section>
<section className="editorial-banner"><img src="/nail-red-1440.webp" srcSet="/nail-red-480.webp 480w, /nail-red-960.webp 960w, /nail-red-1440.webp 1440w" sizes="100vw" width={1440} height={960} loading="lazy" alt="Rich red nail artistry from the Savannah Sky collection"/><div><span className="editorial-label">Make it your own</span><h2>Confidence,<br/><em>at your fingertips.</em></h2></div></section>
<section className="editorial-academy editorial-section"><div><span className="editorial-label">Behind the academy</span><h2>Our world.<br/><em>Your inspiration.</em></h2><p>Step inside Savannah Sky and meet the salon behind your learning.</p><a className="soft-link" href="/about">Meet Savannah Sky <ArrowUpRight size={16}/></a></div><img src="/academy-portrait-960.webp" width={960} height={1440} loading="lazy" alt="The educator behind Savannah Sky in the salon"/></section>
<Reviews/>
<section className="editorial-faq editorial-section"><div className="editorial-centered"><span className="editorial-label">Good to know</span><h2>A few little <em>questions.</em></h2></div><div>{questions.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><a className="soft-link" href="/faq">All your questions, answered <ArrowUpRight size={16}/></a></section>
<section className="editorial-join editorial-section"><span className="editorial-label">Make space for yourself</span><h2>Your next chapter<br/><em>starts here.</em></h2><a className="button" href="/courses">Explore the academy <ArrowUpRight size={16}/></a></section>
<div className="editorial-photo-strip" aria-hidden="true">{['floral','sculpted','leopard','red'].map(name=><img key={name} src={'/nail-'+name+'-480.webp'} width={480} height={480} alt="" loading="lazy"/>)}</div></div>}
