const paragraphs = [
"Before coming to Savannah Sky Salon, I had never touched a single nail. After having my two children and spending time on maternity leave, I found myself feeling a little lost, unsure of who I was and what I wanted to do next. Then I was given an opportunity that genuinely changed my life: the chance to learn and train as a nail technician with Carla at Savannah Sky Salon.",
"Carla is so much more than an amazing teacher. She is attentive, patient, encouraging, fun and incredibly supportive. She has a real talent for teaching, making even the things that seem daunting at first feel achievable. She takes the time to explain things properly, shares her knowledge and experience so generously, and encourages you to believe in yourself even when you doubt your own abilities. She wants you to succeed, not just as a nail technician, but as a person, and that really shines through in the way she teaches. She gives the best advice, is always there when you need her and genuinely cares about the people she trains.",
"Savannah Sky Salon is so much more than a salon. It is a special place filled with support, laughter, encouragement and people who want to see you do well. For me, it has become one of my safe spaces, somewhere I feel comfortable, supported and able to be myself.",
"Looking back at how much has changed in just one year is incredible. The opportunities Carla has given me have helped me find my confidence again, discover something I genuinely love and build a future for myself and my family. I now have a job I love, have started my own business, Polished by Brogan, and am working self-employed at Savannah Sky Salon. I never imagined I would have achieved all of this when I first walked through the door knowing absolutely nothing about nails!",
"This opportunity has given me so much more than a qualification. It has given me confidence, independence, a passion, a sense of purpose and the belief that I can achieve things I never thought possible. As a mum of two, being able to build something for myself while creating a better future for my family means more to me than words can explain.",
"Choosing to train with Carla was genuinely one of the best things I have ever done for myself and my family. I will always be grateful for the chance she gave me, for everything she has taught me and for the support she continues to give me. She doesn't just teach you how to do nails; she helps you believe in yourself and see what you are capable of.",
"I honestly couldn't recommend Carla and Savannah Sky Salon enough. If you're thinking about taking that first step into the nail industry, I would say go for it. You never know where that one opportunity might lead you. Mine has changed my life, and I will always be thankful for that. ❤️"
];
export default function StudentStory(){return <section className="student-story" aria-labelledby="brogan-story"><div className="student-story-intro"><span className="eyebrow">A STUDENT’S STORY</span><h2 id="brogan-story">Finding confidence.<br/>Building a future.</h2><p>Brogan’s experience of training with Carla at Savannah Sky Salon.</p></div><div className="student-story-content"><figure><blockquote>“She doesn't just teach you how to do nails; she helps you believe in yourself and see what you are capable of.”</blockquote><figcaption><strong>Brogan</strong><span>Polished by Brogan</span></figcaption></figure><details><summary>Read Brogan’s full story<span aria-hidden="true">＋</span></summary><div className="student-story-full">{paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div></details></div></section>}
