import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const courses=sqliteTable('courses',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull(),level:text('level').notNull(),price:integer('price'),paymentUrl:text('payment_url'),courseUrl:text('course_url'),thumbnailKey:text('thumbnail_key'),outcomes:text('outcomes'),requirements:text('requirements'),duration:text('duration'),accessPolicy:text('access_policy'),published:integer('published').notNull().default(0)});
export const lessons=sqliteTable('lessons',{id:text('id').primaryKey(),courseId:text('course_id').notNull(),title:text('title').notNull(),body:text('body').notNull(),videoKey:text('video_key'),thumbnailKey:text('thumbnail_key'),videoUrl:text('video_url'),resourceUrl:text('resource_url'),question:text('question'),options:text('options'),answer:integer('answer'),position:integer('position').notNull().default(0)},t=>[index('idx_lessons_course').on(t.courseId)]);
export const enrollments=sqliteTable('enrollments',{id:text('id').primaryKey(),email:text('email').notNull(),courseId:text('course_id').notNull()},t=>[index('idx_enrollment_email_course').on(t.email,t.courseId)]);
export const progress=sqliteTable('progress',{id:text('id').primaryKey(),userId:text('user_id').notNull(),lessonId:text('lesson_id').notNull(),completedAt:text('completed_at').notNull()});
export const enquiries=sqliteTable('enquiries',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),message:text('message').notNull(),createdAt:text('created_at').notNull()});

export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull()},t=>[index('idx_profile_email').on(t.email)]);

export const settings=sqliteTable('settings',{id:text('id').primaryKey(),value:text('value').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),email:text('email').notNull(),courseId:text('course_id').notNull(),title:text('title').notNull(),amount:integer('amount').notNull(),currency:text('currency').notNull().default('gbp'),status:text('status').notNull().default('pending'),sessionId:text('session_id'),mode:text('mode').notNull(),createdAt:text('created_at').notNull(),paidAt:text('paid_at')},t=>[index('idx_order_user').on(t.userId)]);
